exclude_patterns:
- debug
- beta
excluded_extensions:
- .zip
- .tar.gz
preferred_extensions:
- .tipa
- .ipa
- .deb
remove_chars:
- -beta
- -alpha
- -dev
replace_chars:
  '-': .
  _: .
strip_v_prefix: true
