name: Compile Repository

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      format:
        description: 'Format to compile (all, altstore, trollapps, scarlet)'
        required: false
        default: 'all'
        type: choice
        options:
          - all
          - altstore
          - trollapps
          - scarlet
      verbose:
        description: 'Enable verbose logging'
        required: false
        default: false
        type: boolean

jobs:
  compile-repo:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Compile Repository Files
        run: |
          args=""
          if ${{ inputs.verbose }}; then args="-v"; fi
          if [ "${{ inputs.format }}" != "all" ]; then args="$args -f ${{ inputs.format }}"; fi
          python3 scripts/compile_repository.py $args

      - name: Commit and Push Changes
        if: success()
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add *.json
          git commit -m "chore: Update repository files (${{ inputs.format }})" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}