name: Compile Repository

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      format:
        description: 'Format to compile (all, altstore, trollapps, scarlet)'
        required: false
        default: 'all'
        type: choice
        options:
          - all
          - altstore
          - trollapps
          - scarlet
      verbose:
        description: 'Enable verbose logging (true or false)'
        required: false
        default: false
        type: boolean

jobs:
  compile-repo:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
        
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
    
      - name: Install dependencies
        run: |
          pip install requests pyyaml

      - name: Compile Repository Files
        run: |
          args=""
          [ "${{ github.event.inputs.verbose }}" = "true" ] && args="-v"
          [ "${{ github.event.inputs.format }}" != "all" ] && args="$args -f ${{ github.event.inputs.format }}"
          echo "Starting compilation with args: $args"
          python3 scripts/compile_repository.py $args

      - name: Debug Generated Files
        run: ls -la *.json || echo "No JSON files found"

      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add *.json
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: Update ${{ github.event.inputs.format || 'all' }} repository files [skip ci]"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}