name: Compile Repository

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      format:
        description: 'Format to compile (altstore, trollapps, scarlet, or empty for all)'
        required: false
        default: ''
        type: choice
        options:
          - ''
          - altstore
          - trollapps
          - scarlet

jobs:
  compile-repo:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    
    - name: Run compilation
      run: |
        python3 scripts/compile_repo.py "${{ github.event.inputs.format }}"

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add *.json
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "chore: Update ${{ github.event.inputs.format || 'all' }} repository files [skip ci]"
          git push
        fi