name: Manage Versions (FAST)

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:
    inputs:
      action:
        description: 'Action (update/remove)'
        required: true
        type: choice
        options:
          - update
          - remove
        default: 'update'  # Default for manual runs
      app_list:
        description: 'Comma-separated app names (leave empty for all)'
        required: false
        type: string
      keep_versions:
        description: 'Number of versions to keep (update only)'
        required: true
        type: number
        default: 10

jobs:
  manage-versions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip

    - name: Install dependencies
      run: |
        pip install requests
    
    - name: Run version management
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Use scheduled run defaults or workflow_dispatch inputs
        ACTION: ${{ github.event_name == 'schedule' && 'update' || inputs.action }}
        KEEP_VERSIONS: ${{ github.event_name == 'schedule' && 10 || inputs.keep_versions }}
        APP_LIST: ${{ inputs.app_list }}
      run: |
        IFS=',' read -ra APPS <<< "$APP_LIST"
        for app in "${APPS[@]}"; do
          python3 scripts/manage_versions.py "$ACTION" "$KEEP_VERSIONS" "$app"
        done
        
        if [ -z "$APP_LIST" ]; then
          python3 scripts/manage_versions.py "$ACTION" "$KEEP_VERSIONS"
        fi
    
    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add Apps/
        git commit -m "chore: Version $ACTION (keep $KEEP_VERSIONS) for ${{ inputs.app_list || 'all apps' }}" || echo "No changes to commit"
        git push