name: Nightly Automation

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  trigger-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger version updates
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/DRKCTRL/DRKSRC/actions/workflows/manage_versions.yml/dispatches" \
          -d '{"ref":"main", "inputs": {"action": "update", "keep_versions": 10}}'

      - name: Trigger repository compilation
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/DRKCTRL/DRKSRC/actions/workflows/compile_repository.yml/dispatches" \
          -d '{"ref":"main", "inputs": {"featured_count": 5, "format": ""}}'