name: Nightly Repository Update

on:
  schedule:
    - cron: '0 0 * * *'  # Run at midnight UTC daily
  workflow_dispatch:  # Allow manual triggers

# Add these permissions
permissions:
  contents: write
  pull-requests: write

jobs:
  update-repository:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests packaging
    
    - name: Configure Git
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
    
    - name: Update Repository
      run: |
        python scripts/update_repository.py
    
    - name: Commit and Push Changes
      run: |
        git add -A
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "🤖 Automated repository update"
          git push
        fi
