name: Update App Metadata (SLOW)

on: 
  workflow_dispatch:
    inputs:
      app_name:
        description: 'App name to update (leave empty for all)'
        required: false
        type: string

jobs:
  update-metadata:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pillow plistlib
    
    - name: Run metadata extraction
      run: |
        if [ -n "${{ inputs.app_name }}" ]; then
          python3 scripts/update_metadata.py "${{ inputs.app_name }}"
        else
          python3 scripts/update_metadata.py
        fi
    
    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add Apps/
        git commit -m "chore: Update ${{ inputs.app_name || 'all apps' }} metadata" || echo "No changes to commit"
        git push